title: "Мій сайт"
description: "Це мій перший сайт на Jekyll!"
url: ""
baseurl: ""  # Якщо сайт буде в кореневій директорії, це залишити порожнім
theme: "minimal-mistakes-jekyll"  # Вказуємо тему, яку ти використовуєш

