title: "Мій сайт"
description: "Це мій перший сайт на Jekyll!"
url: "https://example.com"
baseurl: ""  # Якщо сайт буде в кореневій директорії, це залишити порожнім
theme: "minimal-mistakes"  # Вказуємо тему, яку ти використовуєш

